### ISSUE TITLE
Stepping over enhanced for loop steps into javascript

### ISSUE THREAD

**Issue by rdwallis** [sdbg/sdbg#100]
If you place a breakpoint before an enhanced for loop and then step over the loop.  SDBG will step you into javascript source.

Probably the fix needs to be tested separately on Collection and Array loops since they're translated into a different number of statements in the javascript source.

**Comment by ivmarkov** [comment]
This does not happen in Chrome Devtools, or does it?

**Comment by rdwallis** [comment]
No it doesn't happen in devtools but you have to step over multiple times on the for loop line before it progresses you to the next line.

**Comment by seamusmac** [comment]
Is there anything we can do to improve the experience here? Any pointers where to look in the SDBG code?

I can work around this issue, by setting a breakpoint before, within or after the for loop. But if I am stepping through code and forget this, I end up with SDBG kinda hanging. And have to restart SDBG launch to get back to where I was.

eg. see the attached image. it just sits there trying to load the js file, which I cannot find!

![untitled](https://cloud.githubusercontent.com/assets/43647/7480508/de428f56-f360-11e4-9a5d-f117466933e5.png)

**Comment by ivmarkov** [comment]
I'm sorry about this annoyance... I'm also suffering every single time I forget about this bug....

(
BTW: if you are patient enough, and Eclipse has enough RAM transact-0.js WILL load. It is slow because it is being handed FROM the browser TO Eclipse/SDBG. The progress bar hangs simply because Chrome is giving to SDBG the js file as one huge String, rather than properly streaming it. Simply the remote debugging protocol is not well thought out for large javascript files... and the file is huge - this is your whole project compiled without any optimizations by the SDM CodeServer!
)

As for pointers in the SDBG code, it can be tricky...: 
try puttng a breakpoint in 
WebkitDebugThread.java, method stepInto() and another breakpoint in method handleDebuggerSuspended() in the same class.

Now, calling stepInto() should result in a callback in handleDebuggerSuspended(). THe key is the following: when building the array of WebkitDebugStackFrameS, is the top-frame source-mapped or not? Apparently, SDBG decides that it is not sourcemapped, and therefore rather than the Java file, it loads the raw JS compiled output.

**Comment by ivmarkov** [comment]
Fixed, V >= 1.0.6
