### ISSUE TITLE
error on launch: "Unable to connect to Chrome: Can't assign requested address"

### ISSUE THREAD

**Issue by skybrian** [sdbg/sdbg#112]
Hi, although I've used SDBG before, now when I start it, I get an error in a dialog box from Eclipse:

  Unable to connect to Chrome: Can't assign requested address

I am using "Launch Chrome" and it does launch the browser with the correct URL. The error persists even after a reboot.

No doubt it is a silly configuration problem somewhere, but I think this error message could be improved: what host and port is it trying to use? Perhaps there should be a way to change the port to avoid a conflict?

**Comment by ivmarkov** [comment]
The message is improved (BETA V >= 1.0.4, to be released in a couple of hours):
* It displays a different message depending on whether the problem was when connecting to the Chrome initial port (usu 9222) or to the Chrome tab's debug port
* It also displays the host and port

Other than that, the error seems to come from the Apple networking stack, but google is not finding anything useful: http://apple.stackexchange.com/questions/114115/network-stops-working-with-cant-assign-requested-address
