### ISSUE TITLE
"Can't assign requested address" error when Chrome config is Run instead of Debugged

### ISSUE THREAD

**Issue by skybrian** [sdbg/sdbg#113]
To reproduce, create a "Launch as Chrome" configuration. Notice that this configuration shows up in both the "Debug" menu and the "Run" menu.

If you launch the configuration using the "Debug" menu, the debugger works. If you launch it using the "Run" menu, then you will get a popup saying "Unable to connect to Chrome: Can't assign requested address".

**Comment by skybrian** [comment]
The popup shows up after delay (several seconds). Probably a timeout.

I think there are two problems:

(1) It appears that SDBG attempts to open a connection to the Chrome debug port even when it didn't launch Chrome for debugging.

(2) Even if (1) is fixed by not attempting to connect to the debug port, it's rather difficult for the user to know what they did wrong. It's logical in retrospect that if you don't use the debug menu then debugging won't work, but it may be unclear why.

There's little point in using the "Launch in Chrome" config except to debug, so this seems like an unnecessary stumbling block.

Possible solutions:

(a) Make "Launch in Chrome" behave the same way in both menus so it doesn't matter which one you pick.
(b) Remove or disable the "Launch Chrome" configuration in the "Run" menu.
(c) Somehow tell the user that Chrome is being launched without debugging being turned on.

**Comment by ivmarkov** [comment]
Apparently I've regressed the code (probably when implementing support for Mobile Chrome), as the original codebase from DART did allow "running" the browser (btw for whatever reason, behind the scenes the "running" was implemented as an actual debug session with breakpoints disabled).

Anyway, I agree (b) or (c) makes a lot of sense.

**Comment by ivmarkov** [comment]
OK I've pushed a fix which will appear in V1.0.4 shortly.

The fix still allows for "running" Chrome if the user has invoked Launch Chrome from the Run menu. However unlike DART, I'm really running the browser, without opening any debug connection.

Opening a warning dialog to the user explaining that he is only running Chrome as opposed to debugging, turned out to be surprisingly difficult because of the code/UI plugin separation in Eclipse & SDBG. In case people still often get confused, I'll probably go for option (b) and remove the debug configuration from appearing in the "Run" menu.

Debugging:
![debugging](https://cloud.githubusercontent.com/assets/2607589/5988795/2f8e4f90-a978-11e4-9757-9e38187f46fc.png)


Running:
![running](https://cloud.githubusercontent.com/assets/2607589/5988796/3e13dd82-a978-11e4-8486-de0843cb803e.png)
