### ISSUE TITLE
longs omitted from logical view

### ISSUE THREAD

**Issue by skybrian** [sdbg/sdbg#114]
It looks like the new logical view omits longs entirely.

Long values are treated specially. They're compiled to a JavaScript object, but represent a primitive value. For more see this document I've recently started:

https://docs.google.com/document/d/1-of2yVcVVzOeaOh6AUjFfuM3_6WgR8nEwkXM_wBCPXo/edit#heading=h.hvtrfnjis3r

**Comment by ivmarkov** [comment]
Thanks for the document - looks good. You are correct - there is no special treatment of longs at the moment - this is pending.

**Comment by ivmarkov** [comment]
This is implemented now, although there is a small bug in that in the details pane below in the Variables view, an [Object object] is displayed, instead of the numeric value. This very complex to fix due to Eclipse Logical Structure limitations. In the Value column, the numeric value is correctly rendered though.
