### ISSUE TITLE
Breakpoints are not synchronized between eclipse and chrome

### ISSUE THREAD

**Issue by AlexLuya** [sdbg/sdbg#135]
Hello,
     Both full and partial cases are exist.For full,I mean even all breakpoints got disabled in eclipse,some breakpoints still got triggered during app runs which causes chrome frozen.For partial,if enabling one break point and disabling another,eclipse will tell that enabled one got triggered,then click to continue,the disabled one still got triggered(may other things happens) in chrome which causes chrome frozen,but eclipse won't reflect these.and if I go to chrome,and open develop tool,it will got unfrozen.    

   By the way,my pc has ubuntu 14.04 64bit+chrome 43.0.2357.132 (64-bit)+SSD

**Comment by AlexLuya** [comment]
Sometimes,within a for loop,first loop will work successfully,then everything is stucked until pressing f12 to bring chrome debug tool up.

**Comment by seamusmac** [comment]
I find this quite annoying also. When in a for loop, or some method that gets called 2 times. The 2nd breakpoint is not caught properly by SDBG. Just leaves chrome hanging. The only way to fix it at the moment is to open the chrome developer tools, which means you lose your debugging session in Eclipse...

**Comment by ivmarkov** [comment]
Thanks for reporting. No promises when, but I'll look into this (also hinders my own efficient work with SDBG as well.)

**Comment by welkman** [comment]
My observations: this only happens when the same breakpoint is hit twice in a row without any other debugger intervention in between other than the "Resume" button.  It does not occur if a different breakpoint is encountered between the first and second hits of the same breakpoint. It does not occur if you use one of the "step" features of the Eclipse debugger ("step over", "step into", "step out") between 1st and 2nd hits of the same breakpoint.  It does not occur if you use "Suspend" after the first hit of the breakpoint but after "Resume".

So the critical path causing the problem is breakpoint #1->"Resume"->breakpoint #1 again.

**Comment by welkman** [comment]
Just to clarify: are we sure the OP problem from @AlexLuya is the same issue as his second post?  The rest of us seem to be commenting on the problem of Chrome hanging on 2 successive hits of the same breakpoint, whereas the OP seemed to be about whether the enabled/disabled status of the breakpoints are honored.

FYI, I am experiencing this on 64-bit Windows 7 with Chrome 46.0.2490.80 m

**Comment by AlexLuya** [comment]
This issue comes up randomly.Right now,the break points only are triggered when web page opened in first time.Follow through refreshing won't trigger break point

**Comment by welkman** [comment]
I encourage you to look at the details in my first post and reproduce it for yourself.  I think it characterizes things a little more specifically and might provide more insight.  I can get the same breakpoint to trigger multiple times as long as there is at least one different breakpoint or any "step" action taken by the user between subsequent triggers of the original breakpoint.

So for 1-line-body for-loops, since you can't set a 2nd breakpoint in the body, the solution is to use "step" for each loop rather than "resume".

**Comment by AlexLuya** [comment]
ubuntu 14.04 64bit+chrome  46.0.2490.86 (64-bit)+eclipse 4.5+sdbg 1.0.6,no breakpoint got hitted.

**Comment by AlexLuya** [comment]
This is definitely a very serious bug of this plugin,why doesn't it be marked as bug?

**Comment by ivmarkov** [comment]
You could help by providing more concrete steps to reproduce. Ideally, with the sample app on the website. You know, like STEP 1: put a breakpoint on line XXX in file XXX. STEP 2: hit F5. etc. etc.

**Comment by ivmarkov** [comment]
Fixed, V >= 1.0.9 (to be released shortly)

**Comment by ivmarkov** [comment]
A fix for this is likely available in the newly released version in the BETA P2 repo:
http://sdbg.github.io/p2beta/

That's thanks to #145

**Comment by seamusmac** [comment]
I just tried the p2beta, and can confirm that most the issues are now resolved. 

Great work!!! :+1:

**Comment by seamusmac** [comment]
Is there an official release in the works with this fix?

**Comment by ivmarkov** [comment]
I moved the beta release to the main/production repository long ago. Are you still seeing the problem?

**Comment by seamusmac** [comment]
Ah ok, I wasn't sure if it was out yet or not. https://github.com/sdbg/sdbg/releases says last release was in Feb, but this was only fixed in March so I wasn't sure. Good to know that it was pushed out. I was just using the beta. I will try the official release when I have time.

**Comment by ivmarkov** [comment]
I must admit I actually hadn't moved the beta release to production (blush).

I just did it now.
