### ISSUE TITLE
javax.xml.bind.DatatypeConverter not found when running Eclipse with Java11

### ISSUE THREAD

**Issue by axeluhl** [sdbg/sdbg#161]
When Eclipse 2018_09 is run with an OpenJDK 11, SDBG won't find javax.xml.bind.DatatypeConverter which is a show stopper for debugging GWT applications.

**Comment by ivmarkov** [comment]
Please paste the full stack trace so I can figure out which component requires the javax.xml.bind stuff. Thanks.

**Comment by axeluhl** [comment]
ava.io.IOException: java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
	at com.github.sdbg.debug.core.internal.webkit.protocol.WebkitConnection.connect(WebkitConnection.java:198)
	at com.github.sdbg.debug.core.internal.webkit.model.WebkitDebugTarget.openConnection(WebkitDebugTarget.java:337)
	at com.github.sdbg.debug.core.internal.util.BrowserManager.connectToChromiumDebug(BrowserManager.java:514)
	at com.github.sdbg.debug.core.internal.util.BrowserManager.launchBrowser(BrowserManager.java:333)
	at com.github.sdbg.debug.core.configs.ChromeLaunchConfigurationDelegate.doLaunch(ChromeLaunchConfigurationDelegate.java:97)
	at com.github.sdbg.debug.core.SDBGLaunchConfigurationDelegate.launch(SDBGLaunchConfigurationDelegate.java:51)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:862)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:720)
	at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1029)
	at org.eclipse.debug.internal.ui.DebugUIPlugin$2.run(DebugUIPlugin.java:1243)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
	at de.roderick.weberknecht.WebSocketHandshake.encodeBase64String(WebSocketHandshake.java:113)
	at de.roderick.weberknecht.WebSocketHandshake.createNonce(WebSocketHandshake.java:109)
	at de.roderick.weberknecht.WebSocketHandshake.<init>(WebSocketHandshake.java:36)
	at de.roderick.weberknecht.WebSocket.<init>(WebSocket.java:72)
	at com.github.sdbg.debug.core.internal.webkit.protocol.WebkitConnection.connect(WebkitConnection.java:158)
	... 10 more
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter cannot be found by com.github.sdbg.debug.core_1.0.10.201710010135
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:511)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:422)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:414)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:153)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 15 more
![screenshot from 2019-01-02 22-00-51](https://user-images.githubusercontent.com/483006/50612419-38327100-0eda-11e9-8054-9a81bf0dcd28.png)
![screenshot from 2019-01-02 22-00-08](https://user-images.githubusercontent.com/483006/50612658-040b8000-0edb-11e9-8589-540d57b3b5ad.png)

**Comment by cristian-spiescu** [comment]
I'm having this issue as well. I'm wondering: are there plans to update the plugin in order to make it compatible with Java 11?

**Comment by ivmarkov** [comment]
Yes, I would like to fix this issue, yet simply can't find the time recently. I might giver it a shot this weekend, but nevertheless: patches/pull requests very welcome!

**Comment by cherio** [comment]
Same here. This seems to stem from the fact that Java 11 (I didn't try Java 9 and 10) by defult doesn't include module with this class. If only there was a way to put jaxb-api jar on the classpath for SDBG launcher that should solve the problem. I tried to include it into launch configuration as on the screenshot
![Screenshot_2019-07-17_12-27-37_eclipse](https://user-images.githubusercontent.com/2200569/61393266-9fb87880-a88e-11e9-8cfb-4ee504f2ed21.png)
 but that was obviously not the right place

**Comment by ManfredTremmel** [comment]
Hi, I had the same problem after upgrading to Debian Buster (with openJDK 11) and I've done a little workaround which fixed it for me. Sorry, I'm no Eclipse plugin developer, so I don't know how to add new dependencies into the plugin (adding them as maven dependency didn't do the job), but I've seen, there are two jars already included into the project and I've added the javax.xml.bind stuf the same way.

What I've done:

- checkout of the project (`git clone https://github.com/sdbg/sdbg.git`)
- copied [javax.activation-api-1.2.0.jar](https://search.maven.org/remotecontent?filepath=javax/activation/javax.activation-api/1.2.0/javax.activation-api-1.2.0.jar), [jaxb-api-2.3.1.jar](https://search.maven.org/remotecontent?filepath=javax/xml/bind/jaxb-api/2.3.1/jaxb-api-2.3.1.jar), [jaxb-core-2.3.0.1.jar](https://search.maven.org/remotecontent?filepath=com/sun/xml/bind/jaxb-core/2.3.0.1/jaxb-core-2.3.0.1.jar) and [jaxb-impl-2.3.2.jar](https://search.maven.org/remotecontent?filepath=com/sun/xml/bind/jaxb-impl/2.3.2/jaxb-impl-2.3.2.jar) into com.github.sdbg.debug.core/lib/ folder
- added the four jars to the classpath definition of com.github.sdbg.debug.core/META-INF/MANIFEST.MF
- added the four jars to bin.includes definition of com.github.sdbg.debug.core/build.properties
- build stuff with `mvn install`
- add generated com.github.sdbg.releng.p2/target/com.github.sdbg.releng.p2-1.0.10.qualifier.zip file as installation source in eclipse
- update eclipse

Now I can debug my Chromium from Eclipse once again.

Here's the patch file of the action (txt suffix because patch is not supported):
[workaround-for-java-11.patch.txt](https://github.com/sdbg/sdbg/files/3411467/workaround-for-java-11.patch.txt)

**Comment by slavap** [comment]
@ivmarkov Please update http://sdbg.github.io/p2 with fixed Java11 support.

**Comment by cherio** [comment]
The update site doesn't seem to work. It hangs there for a while with a message "Cannot perform operation. Computing alternative solutions ..." and then fails with the message "Cannot complete the request.  See the error log for details. "JavaScript Debugger with Source Mapping Support" will be ignored because it is already installed."

**Comment by morgwai** [comment]
I've uninstalled manually the old version of and then installed SDBG again from http://sdbg.github.io/p2  but still got version 1.0.10.201610081555  :(
seems the release was not pushed.

**Comment by ivmarkov** [comment]
The truth is, I'm no longer supporting this project. Need to find 15 minutes to at least update the website to reflect that.

(At least IMO, the world has moved a bit, and people seem to be jumping on VSCode, which already does have a good JavaScript debugger with sourcemaps...).

**Comment by cherio** [comment]
What about all the GWT projects that rely on IDE debugger for JavaScript? There is no other way to debug a GWT application in Eclipse but through sdbg plugin.

**Comment by ivmarkov** [comment]
I'm pretty sure the Javascript debugger in VSCode does support sourcemaps, so there, the problem does not even exist. Moreover, the Java tooling of VSCode is actually quite OK in the meantime (its Language Server is based on Eclipse actually) even if not yet at the level of classic Eclipse.

Now, if you really want to hold on to the classic Eclipse IDE, there is no other choice but somebody else to start maintaining this debugger. I'm just saying that I personally don't want to do that as I've moved on and I'm no longer an active Eclipse Classic IDE user, nor a GWT user, for that matter.

**Comment by ivmarkov** [comment]
Oh and by the way you can always debug your app inside Chrome itself. It is just that it is a different UI, different keybindings, etc. etc. which makes the experience a bit more annoying of course.

**Comment by slavap** [comment]
@ivmarkov GWT Plugin for Eclipse is the only reason why to stick with Eclipse for GWT development, VSCode does not support GWT well. We are not asking you to develop any new features to SDBG, please just update distribution on http://sdbg.github.io/p2 with the latest code.

**Comment by cherio** [comment]
> @ivmarkov GWT Plugin for Eclipse is the only reason why to stick with Eclipse for GWT development, VSCode does not support GWT well. We are not asking you to develop any new features to SDBG, please just update distribution on http://sdbg.github.io/p2 with the latest code.

That would really be very helpful and a proper way to go :)

**Comment by morgwai** [comment]
> @ivmarkov GWT Plugin for Eclipse is the only reason why to stick with Eclipse for GWT development, VSCode does not support GWT well. We are not asking you to develop any new features to SDBG, please just update distribution on http://sdbg.github.io/p2 with the latest code.

in the meantime it's really easy to build it yourself:
`git clone https://github.com/sdbg/sdbg.git; cd sdbg; JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/ mvn install`
and then in eclipse add local p2 repository located in `sdbg/com.github.sdbg.releng.p2/target/repository/`
takes 10 minutes ;)

**Comment by axeluhl** [comment]
See also https://p2.sapsailing.com/p2/sdbg/ where out build pipeline drops the latest p2 repo built from master.

**Comment by ivmarkov** [comment]
@morgwai @axeluhl You guys want to get maintainer permissions to the sdbg repo?

**Comment by morgwai** [comment]
I actually was trying to have a look at the source (for example to make it compile with Java-11), but couldn't even understand the project structure at all...  ;]   so I guess i'd be quite a useless maintainer at least for now...

I'm trying to convince my employer to hire an engineering-productivity engineer with experience in eclipse plugin development who would exactly take care of sdbg, eclipse-jetty-plugin (broken since jetty-9.4.27 release and completely no support for jetty 10 and 11), maybe improve gwt plugin and few others...  let's hope he will agree  ;)

**Comment by axeluhl** [comment]
> @morgwai @axeluhl You guys want to get maintainer permissions to the sdbg repo?

Sure can't hurt. We have a team here that is developing a GWT application using Eclipse whose back-end is all OSGi. We love being able to debug the full stack from a single tool environment. Maybe we'll find some time soon to look into the process of building and deploying to the official repo.
